### ISSUE TITLE
Calculation in cement-simulation-with-solid-solutions did not converge

### ISSUE THREAD

**Issue by cdeil** [reaktoro/reaktoro-jupyter-book#4]
For me this example notebook doesn't work:
https://reaktoro.org/applications/geochemistry/cement-simulation-with-solid-solutions.html

I get this warning and the results aren't correct:
```
***WARNING***
The chemical equilibrium/kinetics calculation did not converge.
```

This is on MacOS with this conda env: https://github.com/reaktoro/reaktoro-jupyter-book/blob/main/environment.yml

1. Is there some way I can debug and/or fix the issue in my environment (or install some different versions)?
2. Can you reproduce or fix the issue?
3. Maybe we could set up Github CI testing for this or all notebooks?

<img width="1655" alt="Screenshot 2024-01-08 at 14 13 09" src="https://github.com/reaktoro/reaktoro-jupyter-book/assets/852409/0a80f5b3-303b-49ea-9bf5-2d7f734cd0a8">

**Comment by allanleal** [comment]
Hi Christoph, as I tried to update the website this morning (which requires executing all these notebooks) I realized that some examples (such as the one above) were failing. This is due to an update of the equilibrium algorithm in a previous release. I'm working on a fix as we speak. For now, doing the following should solve the issue:

```py
options = EquilibriumOptions()
options.optima.backtracksearch.apply_min_max_fix_and_accept = True

solver = EquilibriumSolver(specs)
solver.setOptions(options)
```

More info on this thread: https://github.com/reaktoro/reaktoro/discussions/344#discussioncomment-7423295

Let me know how this goes.

**Comment by allanleal** [comment]
I still see some warnings, even with the suggested changes above. The results look good however; most likely the algorithm could not resolve some very small amounts of certain species. I'm investigating.

**Comment by cdeil** [comment]
I tried this:

```
# Define equilibrium options
opts = EquilibriumOptions()
opts.optima.output.active = False
opts.epsilon = 1e-13
opts.optima.backtracksearch.apply_min_max_fix_and_accept = True

# Define the equilibrium solver
solver = EquilibriumSolver(specs)
solver.setOptions(opts)
```

Looks better, but there's this glitch:

<img width="1130" alt="Screenshot 2024-01-08 at 15 16 56" src="https://github.com/reaktoro/reaktoro-jupyter-book/assets/852409/7d23cfa5-f6bc-449c-98e6-d89170acf68b">

Great that you were able to reproduce the issue and working on a fix. Thank you!!!

**Comment by allanleal** [comment]
Hi @cdeil , please install the latest version, v2.11.0, and let me know. The Jupyter notebook above has been updated:

https://github.com/reaktoro/reaktoro-jupyter-book/blob/main/applications/geochemistry/cement-simulation-with-solid-solutions.ipynb

This is the new plot:

![bokeh_plot](https://github.com/reaktoro/reaktoro-jupyter-book/assets/5825588/d40ed2fe-5d87-4a66-944f-53861cbbbd10)

In the beginning, for monocarbonate, there is an increase. Later on, it decreases. @gdmiron may know an explanation for this. 

I'll close this issue, but please reopen if issues persists.

**Comment by cdeil** [comment]
It now works and I get the same result with v2.11.0.
Fantastic! Thank you!
