### ISSUE TITLE
Add README?

### ISSUE THREAD

**Issue by cdeil** [reaktoro/reaktoro-jupyter-book#5]
@allanleal  - could you please add a README to this repo?

Just one sentence what it is plus the few common commands to build or test the docs would be very useful for me, as potential contributor to docs to test my edits before making a PR and not being familiar with jupyter-book yet.

**Comment by allanleal** [comment]
Hi Christoph , that would be useful indeed. I've added the steps below to the README. 

1. Create a conda environment with `conda env create -f environment.yml`
2. Activate the created environment `conda activate reaktoro-jupyter-book`
3. Build the project with `jupyter-book build .`
